CREATE TABLE IF NOT EXISTS candles (
    id SERIAL PRIMARY KEY,
    pair TEXT NOT NULL,
    exchange TEXT NOT NULL,
    h DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (h >= 0),
    l DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (l >= 0),
    o DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (o >= 0),
    c DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (c >= 0),
    v DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (v >= 0),
    timestamp BIGINT NOT NULL DEFAULT (
        EXTRACT(
            EPOCH
            FROM
                NOW()
        ) * 1000
    ) :: BIGINT
);
